export const images = {
    bg_wallpaper: require('./source/bg.png'),
    default: require('./source/default.png'),
    header_home_bg: require('./source/header_home_bg.png'),
    tour_image: require('./source/tour_image.png'),
    slide: require('./source/slide.png'),
    home: require('./source/home.png'),
    tour: require('./source/tour.png'),
    favorite: require('./source/favorite.png'),
    user: require('./source/user.png'),
    clock: require('./source/clock.png'),
    calendar: require('./source/calendar.png'),
    location_login: require('./source/location_login.png'),
    header_gradient_bg: require('./source/header_gradient_bg.png'),
    noti: require('./source/noti.png'),
    calendar_home: require('./source/calendar_home.png'),
    avatar: require('./source/avatar.png'),
    bg_result_search: require('./source/bg_result_search.png'),
    detail_tour: require('./source/detail_tour.png'),
    maps: require('./source/maps.png'),
    point_tour: require('./source/point_tour.png'),
    arrow_hori: require('./source/arrow_hori.png'),
    location: require('./source/location.png'),
    not_children: require('./source/not_children.png'),
    children: require('./source/children.png'),
    spin: require('./source/spin.gif'),
};

export type ImageTypes = keyof typeof images;
